data = [
{id: 0, text: "be - was, were - been", form1: "be", form2: "was, were", form3: "been", ru: "быть, являться"},
{id: 1, text: "beat - beat - beaten", form1: "beat", form2: "beat", form3: "beaten", ru: "бить, колотить"},
{id: 2, text: "become - became - become", form1: "become", form2: "became", form3: "become", ru: "становиться"},
{id: 3, text: "begin - began - begun", form1: "begin", form2: "began", form3: "begun", ru: "начинать"},
{id: 4, text: "bend - bent - bent", form1: "bend", form2: "bent", form3: "bent", ru: "гнуть"},
{id: 5, text: "bet - bet - bet", form1: "bet", form2: "bet", form3: "bet", ru: "держать пари"},
{id: 6, text: "bite - bit - bitten", form1: "bite", form2: "bit", form3: "bitten", ru: "кусать"},
{id: 7, text: "blow - blew - blown", form1: "blow", form2: "blew", form3: "blown", ru: "дуть, выдыхать"},
{id: 8, text: "break - broke - broken", form1: "break", form2: "broke", form3: "broken", ru: "ломать, разбивать, разрушать"},
{id: 9, text: "bring - brought - brought", form1: "bring", form2: "brought", form3: "brought", ru: "приносить, привозить, доставлять"},
{id: 10, text: "build - built - built", form1: "build", form2: "built", form3: "built", ru: "строить, сооружать"},
{id: 11, text: "buy - bought - bought", form1: "buy", form2: "bought", form3: "bought", ru: "покупать, приобретать"},
{id: 12, text: "catch - caught - caught", form1: "catch", form2: "caught", form3: "caught", ru: "ловить, поймать, схватить"},
{id: 13, text: "choose - chose - chosen", form1: "choose", form2: "chose", form3: "chosen", ru: "выбирать, избирать"},
{id: 14, text: "come - came - come", form1: "come", form2: "came", form3: "come", ru: "приходить, подходить"},
{id: 15, text: "cost - cost - cost", form1: "cost", form2: "cost", form3: "cost", ru: "стоить, обходиться"},
{id: 16, text: "cut - cut - cut", form1: "cut", form2: "cut", form3: "cut", ru: "резать, разрезать"},
{id: 17, text: "deal - dealt - dealt", form1: "deal", form2: "dealt", form3: "dealt", ru: "иметь дело, распределять"},
{id: 18, text: "dig - dug - dug", form1: "dig", form2: "dug", form3: "dug", ru: "копать, рыть"},
{id: 19, text: "do - did - done", form1: "do", form2: "did", form3: "done", ru: "делать, выполнять"},
{id: 20, text: "draw - drew - drawn", form1: "draw", form2: "drew", form3: "drawn", ru: "рисовать, чертить"},
{id: 21, text: "drink - drank - drunk", form1: "drink", form2: "drank", form3: "drunk", ru: "пить"},
{id: 22, text: "drive - drove - driven", form1: "drive", form2: "drove", form3: "driven", ru: "ездить, подвозить"},
{id: 23, text: "eat - ate - eaten", form1: "eat", form2: "ate", form3: "eaten", ru: "есть, поглощать, поедать"},
{id: 24, text: "fall - fell - fallen", form1: "fall", form2: "fell", form3: "fallen", ru: "падать"},
{id: 25, text: "feed - fed - fed", form1: "feed", form2: "fed", form3: "fed", ru: "кормить"},
{id: 26, text: "feel - felt - felt", form1: "feel", form2: "felt", form3: "felt", ru: "чувствовать, ощущать"},
{id: 27, text: "fight - fought - fought", form1: "fight", form2: "fought", form3: "fought", ru: "драться, сражаться, воевать"},
{id: 28, text: "find - found - found", form1: "find", form2: "found", form3: "found", ru: "находить, обнаруживать"},
{id: 29, text: "fly - flew - flown", form1: "fly", form2: "flew", form3: "flown", ru: "летать"},
{id: 30, text: "forget - forgot - forgotten", form1: "forget", form2: "forgot", form3: "forgotten", ru: "забывать о (чём-либо)"},
{id: 31, text: "forgive - forgave - forgiven", form1: "forgive", form2: "forgave", form3: "forgiven", ru: "прощать"},
{id: 32, text: "freeze - froze - frozen", form1: "freeze", form2: "froze", form3: "frozen", ru: "замерзать, замирать"},
{id: 33, text: "get - got - got", form1: "get", form2: "got", form3: "got", ru: "получать, добираться"},
{id: 34, text: "give - gave - given", form1: "give", form2: "gave", form3: "given", ru: "дать, подать, дарить"},
{id: 35, text: "go - went - gone", form1: "go", form2: "went", form3: "gone", ru: "идти, двигаться"},
{id: 36, text: "grow - grew - grown", form1: "grow", form2: "grew", form3: "grown", ru: "расти, вырастать"},
{id: 37, text: "hang - hung - hung", form1: "hang", form2: "hung", form3: "hung", ru: "вешать, развешивать, висеть"},
{id: 38, text: "have - had - had", form1: "have", form2: "had", form3: "had", ru: "иметь, обладать"},
{id: 39, text: "hear - heard - heard", form1: "hear", form2: "heard", form3: "heard", ru: "слышать, услышать"},
{id: 40, text: "hide - hid - hidden", form1: "hide", form2: "hid", form3: "hidden", ru: "прятать, скрывать"},
{id: 41, text: "hit - hit - hit", form1: "hit", form2: "hit", form3: "hit", ru: "ударять, поражать"},
{id: 42, text: "hold - held - held", form1: "hold", form2: "held", form3: "held", ru: "держать, удерживать, задерживать"},
{id: 43, text: "hurt - hurt - hurt", form1: "hurt", form2: "hurt", form3: "hurt", ru: "ранить, причинять боль, ушибить"},
{id: 44, text: "keep - kept - kept", form1: "keep", form2: "kept", form3: "kept", ru: "хранить, сохранять, поддерживать"},
{id: 45, text: "know - knew - known", form1: "know", form2: "knew", form3: "known", ru: "знать, иметь представление"},
{id: 46, text: "lay - laid - laid", form1: "lay", form2: "laid", form3: "laid", ru: "класть, положить, покрывать"},
{id: 47, text: "lead - led - led", form1: "lead", form2: "led", form3: "led", ru: "вести за собой, сопровождать, руководить"},
{id: 48, text: "leave - left - left", form1: "leave", form2: "left", form3: "left", ru: "покидать, уходить, уезжать, оставлять"},
{id: 49, text: "lend - lent - lent", form1: "lend", form2: "lent", form3: "lent", ru: "одалживать, давать взаймы (в долг)"},
{id: 50, text: "let - let - let", form1: "let", form2: "let", form3: "let", ru: "позволять, разрешать"},
{id: 51, text: "lie - lay - lain", form1: "lie", form2: "lay", form3: "lain", ru: "лежать"},
{id: 52, text: "light - lit - lit", form1: "light", form2: "lit", form3: "lit", ru: "зажигать, светиться, освещать"},
{id: 53, text: "lose - lost - lost", form1: "lose", form2: "lost", form3: "lost", ru: "терять, лишаться, утрачивать"},
{id: 54, text: "make - made - made", form1: "make", form2: "made", form3: "made", ru: "делать, создавать, изготавливать"},
{id: 55, text: "mean - meant - meant", form1: "mean", form2: "meant", form3: "meant", ru: "значить, иметь в виду, подразумевать"},
{id: 56, text: "meet - met - met", form1: "meet", form2: "met", form3: "met", ru: "встречать, знакомиться"},
{id: 57, text: "pay - paid - paid", form1: "pay", form2: "paid", form3: "paid", ru: "платить, оплачивать, рассчитываться"},
{id: 58, text: "put - put - put", form1: "put", form2: "put", form3: "put", ru: "ставить, помещать, класть"},
{id: 59, text: "read - read - read", form1: "read", form2: "read", form3: "read", ru: "читать, прочитать"},
{id: 60, text: "ride - rode - ridden", form1: "ride", form2: "rode", form3: "ridden", ru: "ехать верхом, кататься"},
{id: 61, text: "ring - rang - rung", form1: "ring", form2: "rang", form3: "rung", ru: "звенеть, звонить"},
{id: 62, text: "rise - rose - risen", form1: "rise", form2: "rose", form3: "risen", ru: "восходить, вставать, подниматься"},
{id: 63, text: "run - ran - run", form1: "run", form2: "ran", form3: "run", ru: "бежать, бегать"},
{id: 64, text: "say - said - said", form1: "say", form2: "said", form3: "said", ru: "говорить, сказать, произносить"},
{id: 65, text: "see - saw - seen", form1: "see", form2: "saw", form3: "seen", ru: "видеть"},
{id: 66, text: "seek - sought - sought", form1: "seek", form2: "sought", form3: "sought", ru: "искать, разыскивать"},
{id: 67, text: "sell - sold - sold", form1: "sell", form2: "sold", form3: "sold", ru: "продавать, торговать"},
{id: 68, text: "send - sent - sent", form1: "send", form2: "sent", form3: "sent", ru: "посылать, отправлять, отсылать"},
{id: 69, text: "set - set - set", form1: "set", form2: "set", form3: "set", ru: "устанавливать, задавать, назначать"},
{id: 70, text: "shake - shook - shaken", form1: "shake", form2: "shook", form3: "shaken", ru: "трясти, встряхивать"},
{id: 71, text: "shine - shone - shone", form1: "shine", form2: "shone", form3: "shone", ru: "светить, сиять, озарять"},
{id: 72, text: "shoot - shot - shot", form1: "shoot", form2: "shot", form3: "shot", ru: "стрелять"},
{id: 73, text: "show - showed - shown, showed", form1: "show", form2: "showed", form3: "shown, showed", ru: "показывать"},
{id: 74, text: "shut - shut - shut", form1: "shut", form2: "shut", form3: "shut", ru: "закрывать, запирать, затворять"},
{id: 75, text: "sing - sang - sung", form1: "sing", form2: "sang", form3: "sung", ru: "петь, напевать"},
{id: 76, text: "sink - sank - sunk", form1: "sink", form2: "sank", form3: "sunk", ru: "тонуть, погружаться"},
{id: 77, text: "sit - sat - sat", form1: "sit", form2: "sat", form3: "sat", ru: "сидеть, садиться"},
{id: 78, text: "sleep - slept - slept", form1: "sleep", form2: "slept", form3: "slept", ru: "спать"},
{id: 79, text: "speak - spoke - spoken", form1: "speak", form2: "spoke", form3: "spoken", ru: "говорить, разговаривать, высказываться"},
{id: 80, text: "spend - spent - spent", form1: "spend", form2: "spent", form3: "spent", ru: "тратить, расходовать, проводить (время)"},
{id: 81, text: "stand - stood - stood", form1: "stand", form2: "stood", form3: "stood", ru: "стоять"},
{id: 82, text: "steal - stole - stolen", form1: "steal", form2: "stole", form3: "stolen", ru: "воровать, красть"},
{id: 83, text: "stick - stuck - stuck", form1: "stick", form2: "stuck", form3: "stuck", ru: "втыкать, приклеивать"},
{id: 84, text: "strike - struck - struck, stricken", form1: "strike", form2: "struck", form3: "struck, stricken", ru: "ударять, бить, поражать"},
{id: 85, text: "swear - swore - sworn", form1: "swear", form2: "swore", form3: "sworn", ru: "клясться, присягать"},
{id: 86, text: "sweep - swept - swept", form1: "sweep", form2: "swept", form3: "swept", ru: "мести, подметать, смахивать"},
{id: 87, text: "swim - swam - swum", form1: "swim", form2: "swam", form3: "swum", ru: "плавать, плыть"},
{id: 88, text: "swing - swung - swung", form1: "swing", form2: "swung", form3: "swung", ru: "качаться, вертеться"},
{id: 89, text: "take - took - taken", form1: "take", form2: "took", form3: "taken", ru: "брать, хватать, взять"},
{id: 90, text: "teach - taught - taught", form1: "teach", form2: "taught", form3: "taught", ru: "учить, обучать"},
{id: 91, text: "tear - tore - torn", form1: "tear", form2: "tore", form3: "torn", ru: "рвать, отрывать"},
{id: 92, text: "tell - told - told", form1: "tell", form2: "told", form3: "told", ru: "рассказывать"},
{id: 93, text: "think - thought - thought", form1: "think", form2: "thought", form3: "thought", ru: "думать, мыслить, размышлять"},
{id: 94, text: "throw - threw - thrown", form1: "throw", form2: "threw", form3: "thrown", ru: "бросать, кидать, метать"},
{id: 95, text: "understand - understood - understood", form1: "understand", form2: "understood", form3: "understood", ru: "понимать, постигать"},
{id: 96, text: "wake - woke - woken", form1: "wake", form2: "woke", form3: "woken", ru: "просыпаться, будить"},
{id: 97, text: "wear - wore - worn", form1: "wear", form2: "wore", form3: "worn", ru: "носить (одежду)"},
{id: 98, text: "win - won - won", form1: "win", form2: "won", form3: "won", ru: "победить, выиграть"},
{id: 99, text: "write - wrote - written", form1: "write", form2: "wrote", form3: "written", ru: "писать, записывать"},
];